# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kenny Chen
title2: 
image: profile0.jpg
email: kennychen@nyu.edu
description:
  Welcome! I am a 2nd year Computer Science PhD student at New York University, 
  advised by <a class="links" href="https://qisun.me" target="_blank">Prof. Qi Sun</a>. 
  <br><br>
  During my PhD, I interned at Meta Reality Labs, hosted by <a class="links" href="https://achapiro.github.io/" target="_blank">Alex Chapiro</a>.
  Previously, I received my MS from NYU in 2023 and a BA from UC Berkeley in 2021.
  <br><br>
  I'm happy to chat about research or anything else, and can be reached at <a class="links" href=mailto:kennychen@nyu.edu>kennychen@nyu.edu</a>!

research: My current research interests intersect computer graphics, VR/AR, applied perception, and displays. <br> (Representative papers are <span class="highlight">highlighted</span>, <em>*=equal contribution, †=equal advising</em>)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kenchen10.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 10kenchen
github_username:  kenchen10
google_analytics: G-MEFETL6NEW
# cv: cv.pdf
scholar: QbGH0_AAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
