# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: KENNY CHEN
image: profile0.jpg
email: kc4906@nyu.edu
description:
  Welcome! I am a first year Computer Science PhD student at New York University where I am currently 
  advised by <a class="links" href="https://qisun.me" target="_blank">Prof. Qi Sun</a> 
  in the <a class="links" href="https://www.immersivecomputinglab.org/" target="_blank">Immersive Computing Lab</a>. 
  Recently, I've been really interested in making XR displays more power-efficient. 
  <br><br>
  I graduated with a BA in Computer Science from UC Berkeley, where I pursued research under 
  <a class="links" href="https://people.eecs.berkeley.edu/~sequin/" target="_blank">Prof. Carlo H. Séquin</a>. 
  I was also a TA for <a class="links" href="https://cs184.eecs.berkeley.edu/sp21" target="_blank">Computer Graphics & Imaging</a>,
  and VP of Tech at <a class="links" href="https://www.innovativedesign.club/" target="_blank">Innovative Design</a>.
  <br><br>
  Outside work, I like taking <a class="links" href="images.html" target="_blank">photos</a>, swimming, 
  and playing video games.
  <br><br>
  Feel free to reach out about research or anything else!

research: My current research interests intersect computer graphics, VR/AR, applied perception, and displays. <br> (Representative papers are <span class="highlight">highlighted</span>, <em>*=equal contribution</em>)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kenchen10.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 10kenchen
github_username:  kenchen10
google_analytics: G-MEFETL6NEW
# cv: cv.pdf
scholar: QbGH0_AAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
